sudo: required

language: erlang

otp_release:
    - 18.2.1
    - 17.5

addons:
    apt:
        packages:
            - webfs

services:
    - docker

before_install:
    - git clone --depth=1 https://github.com/letsencrypt/boulder.git boulder
    - cd boulder && docker-compose build
    - cd $TRAVIS_BUILD_DIR

install:
    - ./rebar3 update
    - ./rebar3 compile

before_script:
    - webfsd -p 3099 -r boulder/ -F -L -&
    - boulder/test/run-docker.sh&

script: 
    - make dialize
