os: linux
dist: trusty

language: erlang
otp_release:
    - 22.2

services:
    - docker

addons:
    apt:
        packages:
            - elinks
            - rsyslog

env:
    global:
        - GOPATH=/tmp/go
        - PATH=$GOPATH/bin:$PATH

    #matrix:
        #- BOULDER_BUILD=https://acme-v01.api.letsencrypt.org/build
        #- BOULDER_BUILD=https://acme-staging.api.letsencrypt.org/build

# we only test boulder staging version against last OTP version
#matrix:
#    include:
#        - otp_release: 18.2.1
#          env: BOULDER_BUILD=https://acme-staging.api.letsencrypt.org/build


before_install:
    - wget https://raw.githubusercontent.com/letsencrypt/pebble/master/docker-compose.yml

install:
    - ./rebar3 update
    - DEBUG=1 ./rebar3 as test compile

before_script:
    - docker-compose -f docker-compose.yml up > /tmp/pebble.log&
    - sleep 10
    - curl --request POST --data '{"ip":"10.30.50.1"}' http://localhost:8055/set-default-ipv4

#
script:
    - make dialize
    - DEBUG=1 ./rebar3 ct > /tmp/ct.log 2>&1
#
after_failure:
    - cat /tmp/pebble.log
    - cat /tmp/ct.log
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/suite.log.html
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/letsencrypt_suite.test_*
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/unexpected_io.log.html
#
after_success:
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/suite.log.html
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/letsencrypt_suite.test_*
    - elinks -dump 1 _build/test/logs/ct_run.*/*/run.*/unexpected_io.log.html
    - cat /tmp/pebble.log
