# Here are gathered automatic (generic, pattern-based) rules for Leec.
#
# See GNUmakerules-explicit.inc for the explicit (immediate, static)
# counterparts.


# Prerequisite: LEEC_TOP must be set.


# Add all Leec-specific rules below.


# Outside prerequisites: the modules from Ceylan-Myriad.


# Allows any upper layer to override as a whole the Leec rules used to compile
# classes and other modules:
#
ifndef OVERRIDE_LEEC_BUILD_RULES


endif
